name: ipu_mnist
records_per_epoch: 60000
hyperparameters:
  batch_size: 32
  layer1:
    type: int
    minval: 32
    maxval: 256
searcher:
   name: random
   metric: loss
   max_length: 50
   max_trials: 8
   max_concurrent_trials: 2
max_restarts: 0

# run on graphcore's Docker image with Poplar software and intrumented tensorflow 2.4
environment:
  image: graphcore/tensorflow
# work around det framework - invoke the model directly
entrypoint: python3 ipu.py
# run the workload on 4 IPUs
resources:
  ipus: 4
